### ISSUE TITLE
URL Errors in reference-brick-models

### ISSUE THREAD

**Issue by VladimirAlexiev** [BrickSchema/brick-examples#4]
@gtfierro, @michaelpoplawskipnnl ?
Not sure this is the place to post bugs about https://brickschema.org/resources#reference-brick-models 
- [Gates Hillman Center](https://brickschema.org/ttl/ghc_brick.ttl) `ghc_brick.ttl` has 298 errors due to `%`
- [Engineering Building Unit 3B](https://brickschema.org/ttl/ebu3b_brick.ttl) `ebu3b_brick.ttl` has 5 errors due to `%`
```
Bad IRI: <http://ucsd.edu/building/ontology/ebu3b#EBU3B_RM_3xxx_3rd_FLR_SUPFLO_AVG_%> 
Code: 30/ILLEGAL_PERCENT_ENCODING in FRAGMENT: The host component a percent occurred without two following hexadecimal digits.
```
- [Green Tech House](https://brickschema.org/ttl/gtc_brick.ttl) `gtc_brick.ttl` has over 1800 URL errors due to `[...]`
```
Bad IRI: ... Code: 0/ILLEGAL_CHARACTER in FRAGMENT: The character violates the grammar rules for URIs/IRIs.
eg 48:1 https://brickschema.org/schema/1.0.2/building_example#building:gtc/district_hx/port[po]
```
- `soda_brick.ttl` and `rice_brick.ttl` have no errors

**Comment by gtfierro** [comment]
Thanks for the heads up! This is not the right repository that contains those models, but we are in the middle of updating a bunch of examples in anticipation of the 1.4 release.  I'll make sure I fix the URL errors along with the example models!
